### ISSUE TITLE
Add `Delete Account` Button to User Settings

### ISSUE THREAD

**Issue by Agreon** [Agreon/game-watch#217]
A user should be able to delete his account. Preferably, the button will be located in the lower left corner of the settings modal.
On the server side, a simple call to `uerRepository.delete` is enough to delete all data related to that user

**Comment by Viliam1337** [comment]
Hello, I would like to work on this issue if it's still available.

**Comment by Agreon** [comment]
Yes of course, have fun :) Let me know if you need help

**Comment by Viliam1337** [comment]
Got a few questions : 
1. How important is the pnpm build:docker command from the setup page? I got an error that it doesn't recognize COMPOSE_DOCKER_CLI_BUILD (I'm using Docker Desktop so it's supposed to already have compose installed or at least their website said so). I skipped the step and started all the services anyway and it seems to be working just fine.
2. Just want to be sure : is this where you want the button to be?
![image](https://user-images.githubusercontent.com/115466618/195914895-f42886e5-1e81-4376-a4d4-3c8dc9f02e96.png)
3. Should I also add a confirmation window so that people don't delete their accounts accidentally?

**Comment by Agreon** [comment]
Hey!

1. As long as it works for you, it's fine.  Just to clarify, though: Did you start the services all locally now or did you still use docker?
2. Yes.
3. Yeah that would be a good idea :)

For the button and confirmation window there should be so components from chakra ui you can use.

**Comment by Viliam1337** [comment]
I got the docker running, it was getting ready for about 10 minutes before everything was all good. I'll definitely check out the chakra ui components, thanks for the tip! :D

**Comment by Viliam1337** [comment]
Sorry that it's taking so long. Had to sort some Docker issues as well as manage multiple other projects I'm working on at the same time. Found out Docker Desktop already contains compose, however it still didn't recognize the command to build docker components (or rather, rebuild docker components), so I was unable to rebuild docker components for a few days until I found a workaround using VS Code Docker extension. Also ran into memory shortage issue because WSL which Windows needs to use docker hogged the memory of each rebuild even after deleting old images for whatever reason. Should be ready with PR tomorrow though I believe. Will be ready no later than Monday in worst case.

**Comment by Viliam1337** [comment]
Two more questions I ran into : 
1. where exactly should I write the function that will delete the account? I found multiple server files that use userRepository and could possibly have the function implemented at.
2. by userRepository.delete do you mean userRepositroy.nativeDelete? That is the only suggestion that comes up when typing delete so just want to be sure.

**Comment by Agreon** [comment]
Hey! No worries about the time:)

1: Just do it in the UserController + Userservice
2: Yes, that's perfectly fine for deleting by ID. Just FYI: the Mikro-ORM way is through `remove` but that's not necessary here

**Comment by Viliam1337** [comment]
This took a little longer than I intended, but the issue has been fixed and the app is working as intended. Already submitted a PR.
